package com.example.css

// File is generated by gulp-css-scala

object Css {
  val barAdditional: String = "bar-additional"
  val bazAdditional: String = "baz-additional"
  val fooAdditional: String = "foo-additional"
}