package com.example.css

// File is generated by gulp-css-scala

class Css {
  val bar: String = "bar"
  val barAsBaz: String = "bar--baz"
  val barChildBaz: String = "bar__baz"
  val baz: String = "baz"
  val bazAsFoo: String = "baz--foo"
  val bazChildFoo: String = "baz__foo"
  val foo: String = "foo"
  val fooAsBar: String = "foo--bar"
  val fooAsBarAsBaz: String = "foo--bar--baz"
  val fooAsMedia: String = "foo--media"
  val fooBarBaz: String = "foo-bar-baz"
  val fooChildBar: String = "foo__bar"
  val fooChildBarChildBaz: String = "foo__bar__baz"
}