package com.example.css

// File is generated by gulp-css-scala

class Css {
  val bar: String = ".bar"
  val barAsBaz: String = ".bar--baz"
  val barChildBaz: String = ".bar__baz"
  val baz: String = ".baz"
  val bazAsFoo: String = ".baz--foo"
  val bazChildFoo: String = ".baz__foo"
  val foo: String = ".foo"
  val fooAsBar: String = ".foo--bar"
  val fooChildBar: String = ".foo__bar"
}